### ISSUE TITLE
Issue with reference FASTA file in running ESPRESSO_S.pl

### ISSUE THREAD

**Issue by jamesoccean** [Xinglab/espresso#12]
Hello,

I am trying to run ESPRESSO_S.pl but running into an error with using the FASTA file that I used in the mapping stage. I keep receiving an error that reads, for instance, 

`Don't know what format AGGATGACATCACAGAGAACATTCAGGCCTCAAACCTAAATATTCAGATCTGAGGTTGGG is!
CTTCCCCAGCCCCGCCCCCTCACTTCCGGTCGGACCGCACTGGGCAGAAGCCCGTG in genome.fa does not exist or is not readable!
Don't know what format CTTCCCCAGCCCCGCCCCCTCACTTCCGGTCGGACCGCACTGGGCAGAAGCCCGTG is!`

Should I make any adjustments to the FASTA file before running ESPRESSO_S.pl? I also tried using a transcripts FASTA file to no avail.

**Comment by EricKutschera** [comment]
It looks like this is the line that gives that error: https://github.com/Xinglab/espresso/blob/v1.3.0-beta/src/ESPRESSO_S.pl#L169

That code is for parsing the sample file given on the commandline with -L (or --list_samples). Can you check the arguments in your command to see if genome.fa is used with -L (instead of -F)

**Comment by jamesoccean** [comment]
Thank you- it works! Error on my part.
