### ISSUE TITLE
compare AS events identified from rmats with espresso transcripts

### ISSUE THREAD

**Issue by yuejun-j-wang** [Xinglab/espresso#28]
Hi,

I want to compare the AS events identified from short reads with rmats to espresso long-read transcripts, so I can calculate that how many AS events can be verified by long reads, how can I achieve this. Can I use rmats results as gtf input for espresso, but how can I retrieve the gtf file from rmats results?

**Comment by EricKutschera** [comment]
rmats does not output a gtf file since it doesn't quantify full length transcripts. Instead rmats outputs individual alternative splicing events. You could run rmats and espresso separately, but using the same reference gtf as input to both. Then for each detected AS event in the rmats output you could check the espresso output gtf to see if both isoforms of the AS event are supported by the gtf. The rmats output format is described in the README: https://github.com/Xinglab/rmats-turbo#output
