### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by LPChaumont** [Xinglab/espresso#46]
Hi,

I was eager to try Espresso, but I have a problem with the conda installation from https://anaconda.org/bioconda/espresso. After creating a fresh conda environment and installing espresso with `mamba install -c bioconda espresso`, I tried running the test data following the github instructions. The command `perl ESPRESSO_S.pl -A SIRV_C.gtf -L samples.tsv -F SIRV2.fasta -O test_sirv` gives me the error `Can't open perl script "ESPRESSO_S.pl": No such file or directory`. The perl script is present at ~/miniconda3/envs/espresso/bin/ESPRESSO_S.pl. My Espresso environment was active and all the test data files were in the working directory. My local machine runs Ubuntu 22.04.3 LTS and I had the same error message when trying to run Espresso on a HPC cluster. 

Thank you very much!

**Comment by EricKutschera** [comment]
You should be able to use the full path for the `.pl` file: `perl ~/miniconda3/envs/espresso/bin/ESPRESSO_S.pl ...`. In that example command you need the full paths for files that aren't in the current directory: `perl ./conda_env/bin/ESPRESSO_S.pl -A ./test_data/test_data_espresso_sirv/SIRV_C.gtf -L samples.tsv -F ./test_data/test_data_espresso_sirv/SIRV2.fasta -O test_sirv`

**Comment by LPChaumont** [comment]
Thank you for your quick response! Using the full path for the `.pl` file works.

**Comment by LPChaumont** [comment]
Would it be practical to add the visualization script to the conda package to have everything together? Thank you again for your help, ESPRESSO works well!

**Comment by EricKutschera** [comment]
The conda package could use some work, but there are other aspects of ESPRESSO that are higher priority for me to work on

The conda package has the `ESPRESSO_*` perl files copied to `bin/`: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/espresso/build.sh

That's fine for the ESPRESSO files since the names make it unlikely to conflict with any other packages. Copying the visualization scripts to `bin/` doesn't make sense because those files have names that could easily conflict (visualize.py)

Ideally all the necessary files for ESPRESSO could be packaged up in some way (perl module, python package, ...) with just a single executable file like `bin/espresso` that allows using the various parts of the ESPRESSO code: `espresso C ...` or `espresso visualize ...`. I'm not sure what the best way is to package things up

For now you can use the visualization scripts from the github repo. There's also https://github.com/Xinglab/rMATS-long which is available in bioconda and can make visualizations from ESPRESSO output
