### ISSUE TITLE
Problems when running ESPRESSO_C.pl ，trying to run the snakemake workflow also has problems.

### ISSUE THREAD

**Issue by happypiggyzjx** [Xinglab/espresso#74]
Dear espresso development team:
Greetings~

Allow me to describe to you the problem I'm having: when using the command ESPRESSO_C.pl, I'm running the code as follows:
perl /home/zhaojiaxin/anaconda3/envs/espresso/bin/ESPRESSO_C.pl \
-I /cold_data/zhaojiaxin/rmatslr/0 \
-F /hot_warm_data/wangduo/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
-X 0

But encountered the following error message:
Parasail.c: loadable library and perl binaries are mismatched (got handshake key 0xed00080, needed 0xeb00080)

I've tried everything including updating Parasail.c, perl, etc. and didn't get a good solution, so I decided to try your packaged snakemake workflow. I did the following: create a new empty environment named snakemake, install snakemake via anaconda, clone the espresso repository from github to the folder /cold_data/zhaojiaxin/ensembl/rmatslr and go to . /espresso/snakemake.

Immediately after that I ran . /install, everything worked fine, and a new, unnamed conda environment was created: /cold_data/zhaojiaxin/ensembl/rmatslr/espresso/snakemake/conda_env, which I accessed (and which is still in the working directory /cold_data/ zhaojiaxin/ensembl/rmatslr/espresso/snakemake), run . /run and encountered the following error message:
Using profile ./snakemake_profile for setting default command line arguments.
KeyError in file /cold_data/zhaojiaxin/ensembl/rmatslr/espresso/snakemake/Snakefile, line 210:
'guppy_bin_path'
  File "/cold_data/zhaojiaxin/ensembl/rmatslr/espresso/snakemake/Snakefile", line 210, in <module>

To make it easier for you to check the cause of my error, please allow me to paste the contents of my own modified snakemake_config.yaml file below. The starting file I want to use is the bam file of minimap2, theoretically it doesn't need guppy, why do I still get the following error message? And how can I correct it? Sincerely looking forward to your professional reply, have a nice day ☀!

snakemake_config.yaml：
# Resource allocation
guppy_gpu_name: 'a100'
guppy_gpus: 1
guppy_mem_gb: 48
guppy_threads: 20
guppy_time_hr: 48
combine_c_for_q_mem_gb: 8
combine_c_for_q_time_hr: 12
create_corrected_sams_mem_gb: 16
create_corrected_sams_threads: 10
create_corrected_sams_time_hr: 48
espresso_c_mem_gb: 32
espresso_c_threads: 4
espresso_c_time_hr: 12
espresso_q_mem_gb: 64
espresso_q_threads: 8
espresso_q_time_hr: 12
espresso_s_mem_gb: 64
espresso_s_threads: 6
espresso_s_time_hr: 12
minimap2_mem_gb: 48
minimap2_threads: 10
minimap2_time_hr: 48
split_s_for_c_mem_gb: 4
split_s_for_c_time_hr: 12
visualize_mem_gb: 40
# Command options
use_annotated_junctions_with_minimap2: true
keep_espresso_c_temp: false
use_blast: false
use_alignment_read_groups: false
output_compatible_isoforms: false
output_corrected_sam_files: false
corrected_sam_aligner_window: 400
target_reads_per_espresso_c_job: 400000
# Visualization options
enable_visualization: false
vis_normalize_counts: false
vis_target_gene: ''
vis_minimum_count: 1
vis_descriptive_name: 'ESPRESSO'
# Reference files:
# The snakemake can automatically download and gunzip files if
# a matching url entry is given in the reference_files section below.
# If the entry in the reference_files section ends with .gz then the
# snakemake will gunzip the file.
# **The gtf_name and fasta_name should not end with .gz**
gtf_name: 'Homo_sapiens.GRCh38.109.gtf'
fasta_name: 'Homo_sapiens.GRCh38.dna.primary_assembly.fa'
# The entries under reference_files should be
# file_name.with.extension:
#   url: 'url_path/to_the/file_name.with.extension'
#
# The 'url:' will be used to download the file and it will be put in
# references/ with the name given on the line above the 'url:'.
# The file will be gunzipped and the .gz removed if needed.
# reference_files:
# Homo_sapiens.GRCh38.109.gtf:
# url: '/hot_warm_data/wangduo/reference/Homo_sapiens.GRCh38.109.gtf'
# Homo_sapiens.GRCh38.dna.primary_assembly.fa:
# url: '/hot_warm_data/wangduo/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa'
# Input samples:
# Each sample name will have a separate column in the abundance.esp output file.
# Replicates can be given as separate sample names
# (sample_1_rep_1, sample_1_rep_2, ...) to have the abundance counted separately.
# Alternatively, replicates can be listed under the same sample name to combine
# the counts in the final output.
samples:
  sample_1_name:
    - bam: '/cold_data/wangduo/minimap2/bam/ONT_GRM_R01.sorted.bam'
    - bam: '/cold_data/wangduo/minimap2/bam/ONT_GRM_R07.sorted.bam'
    - bam: '/cold_data/wangduo/minimap2/bam/ONT_GRM_R13.sorted.bam'
  sample_2_name:
    - bam: '/cold_data/wangduo/minimap2/bam/ONT_GRM_R02.sorted.bam'
    - bam: '/cold_data/wangduo/minimap2/bam/ONT_GRM_R08.sorted.bam'
    - bam: '/cold_data/wangduo/minimap2/bam/ONT_GRM_R14.sorted.bam'
# Additional configuration
# libparasail_so_path: '/path/to/libparasail.so'
conda_wrapper: '/cold_data/zhaojiaxin/ensembl/rmatslr/espresso/snakemake/conda_wrapper'
espresso_path: '/cold_data/zhaojiaxin/ensembl/rmatslr/espresso/src'
visualization_path: '/cold_data/zhaojiaxin/ensembl/rmatslr/espresso/visualization'
conda_wrapper: '/cold_data/zhaojiaxin/ensembl/rmatslr/espresso/snakemake/conda_wrapper'
espresso_path: '/cold_data/zhaojiaxin/ensembl/rmatslr/espresso/src'
visualization_path: '/cold_data/zhaojiaxin/ensembl/rmatslr/espresso/visualization'
（By the way, the gtf file as well as the fasta file I have followed the template you gave and cp'd to . /snakemake/references.）

Best,
happypiggy

**Comment by EricKutschera** [comment]
It looks like you removed these two lines from the config:
```
guppy_bin_path: '/path/to/guppy/bin/'
guppy_gpu: false
```
https://github.com/Xinglab/espresso/blob/v1.5.0/snakemake/snakemake_config.yaml#L74

Since you are using `.bam` inputs, the workflow won't actually use guppy, but it still expects to see those lines in the config file. It won't use the values for those keys since the guppy rules won't be run. Here's the line in the Snakefile that raised the error: https://github.com/Xinglab/espresso/blob/v1.5.0/snakemake/Snakefile#L210

The other error, `Parasail.c: loadable library and perl binaries are mismatched (got handshake key 0xed00080, needed 0xeb00080)` happens if different versions of perl are used to build and run the library. Maybe a conda installed perl was used in one case but not the other

**Comment by happypiggyzjx** [comment]
Thank you for your prompt and prompt reply, but regarding the second question, I don't seem to have read your suggested solution to deal with it. I installed the espresso software via anaconda's conda install bioconda::espresso command (meanwhile I only have this one software installed in this conda environment), and when I check the espresso's documentation, it requires that perl ≥ 5.8 and snakemake's conda_ requirements.txt file perl=5.32.*, after that I checked the perl in my own espresso environment and it is 5.34.0.

I tried to reinstall perl in my environment (command: conda install conda-forge::perl), but I still get the following error message, what should I do now to solve this problem? Sincerely looking forward to your reply~
![Snipaste_2024-09-06_14-30-09](https://github.com/user-attachments/assets/cb4f610c-e536-40ed-bed3-41fe71c1f8da)

**Comment by happypiggyzjx** [comment]
As well as about the first snakemake process I am running again . /run with the following new error (for each sample I encountered the problem circled by the red box and ended up with an error), is this because I am missing the file sbatch?
![Snipaste_2024-09-06_14-40-47](https://github.com/user-attachments/assets/aa72c9c7-0129-4ba2-9168-5f9f12a28219)

**Comment by EricKutschera** [comment]
If you installed espresso from conda then you can check the perl version it expects in the filename for the package in `conda-meta` in the directory for your conda environment. For example `ls conda-meta/espresso*` shows `conda-meta/espresso-1.5.0-pl5321h43eeafb_1.json` which includes `pl5321` for perl 5.32.1. In that file it says which version of perl it depends on: `"perl >=5.32.1,<5.33.0a0 *_perl5"`. The conda installer should have seen that and installed 5.32 instead of 5.34

From the README in `snakemake/`: https://github.com/Xinglab/espresso/tree/v1.5.0/snakemake
The default implementation is for Slurm. Here's where it creates the submit command that uses sbatch: https://github.com/Xinglab/espresso/blob/v1.5.0/snakemake/snakemake_profile/cluster_commands.py#L14

If you're running on an HPC with a different way to submit jobs then you could edit that file to use commands for your system. You can also have jobs run on the local machine by commenting out the cluster related lines in this file: https://github.com/Xinglab/espresso/blob/v1.5.0/snakemake/snakemake_profile/config.yaml#L1
