### ISSUE TITLE
ESPRESSO_S dies

### ISSUE THREAD

**Issue by paulimer** [Xinglab/espresso#8]
Hi all,
I was testing ESPRESSO on a single sam file, but the `ESPRESSO_S` command seems to die at the same point of the `.pl` file.
The `<IN> line` number varies by run.
`Thread 1 terminated abnormally: Died at /home/etheimer/ESPRESSO/src/ESPRESSO_S.pl line 865, <IN> line 88957.`

The command run is the default one : 
```sh
perl ~/ESPRESSO/src/ESPRESSO_S.pl -L ./samples_espresso.tsv -F ~/ref_proj/Homo_sapiens.GRCh38.dna_rm.primary_assembly.fa.gz -A ~/ref_proj/Homo_sapiens.GRCh38.108.gtf -O ./espresso_results
```

Thanks in advance.

**Comment by EricKutschera** [comment]
It looks like this is the line for the error: https://github.com/Xinglab/espresso/blob/v1.3.0-beta/src/ESPRESSO_S.pl#L865

I think that would happen if the chromosome found in the .sam file was not in the provided .fa file

Your command uses `Homo_sapiens.GRCh38.dna_rm.primary_assembly.fa.gz`. ESPRESSO expects the file to be unzipped and doesn't check for a .gz file. Since it didn't read the sequences from the .fa file, ESPRESSO fails to match the chromosome names when reading the .sam file

**Comment by paulimer** [comment]
It was indeed the issue! I don't know why I assumed gzipped fasta was okay. Thanks for the quick answer!
